"""HMAC-signed URLs for the Yandex Disk proxy endpoint.

Public AR viewer pages (reached via QR codes) must be able to fetch media
without a login, but the proxy must never serve arbitrary files. We therefore
sign the ``(path, company_id)`` pair with a time-limited HMAC so that only
URLs generated by the server are accepted by ``GET /api/storage/yd-file``.
"""

from __future__ import annotations

import hashlib
import hmac
import time
from urllib.parse import urlencode

from app.core.config import get_settings

# QR codes are long-lived, so signatures need a generous TTL by default.
DEFAULT_TTL_SECONDS = 60 * 60 * 24 * 30  # 30 days


def _signature(path: str, company_id: int, exp: int) -> str:
    """Return the hex HMAC-SHA256 signature for a media reference."""
    settings = get_settings()
    message = f"{int(company_id)}:{path}:{int(exp)}".encode()
    return hmac.new(
        settings.media_url_secret.encode(), message, hashlib.sha256
    ).hexdigest()


def build_yd_file_url(
    path: str,
    company_id: int,
    ttl_seconds: int = DEFAULT_TTL_SECONDS,
) -> str:
    """Build a signed proxy URL for a Yandex Disk file."""
    exp = int(time.time()) + int(ttl_seconds)
    sig = _signature(path, company_id, exp)
    qs = urlencode(
        {"path": path, "company_id": int(company_id), "exp": exp, "sig": sig}
    )
    return f"/api/storage/yd-file?{qs}"


def verify_yd_file_signature(
    path: str,
    company_id: int,
    exp: int | str | None,
    sig: str | None,
) -> bool:
    """Return True when *sig* is a valid, unexpired signature for the reference."""
    if not sig or exp is None:
        return False
    try:
        exp_int = int(exp)
    except (TypeError, ValueError):
        return False
    if exp_int < int(time.time()):
        return False
    expected = _signature(path, company_id, exp_int)
    return hmac.compare_digest(expected, sig)
