"""add marker fields to ar_content table

Revision ID: e90dda773ba4
Revises: a24b93e402c7
Create Date: 2025-12-18 22:33:41.495013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e90dda773ba4'
down_revision: Union[str, None] = 'a24b93e402c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ar_content', sa.Column('marker_path', sa.String(length=500), nullable=True))
    op.add_column('ar_content', sa.Column('marker_url', sa.String(length=500), nullable=True))
    op.add_column('ar_content', sa.Column('marker_status', sa.String(length=50), nullable=True))
    op.add_column('ar_content', sa.Column('marker_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_content', 'marker_metadata')
    op.drop_column('ar_content', 'marker_status')
    op.drop_column('ar_content', 'marker_url')
    op.drop_column('ar_content', 'marker_path')
    # ### end Alembic commands ###
