"""create_tables_from_models

Revision ID: 3d2b8a4fd05b
Revises: 5eac18e27a8d
Create Date: 2025-12-15 17:19:30.180720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d2b8a4fd05b'
down_revision: Union[str, None] = '5eac18e27a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем таблицы с CASCADE для корректного удаления зависимостей
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE")
    op.execute("DROP TABLE IF EXISTS notifications CASCADE")
    op.execute("DROP TABLE IF EXISTS email_queue CASCADE")
    op.execute("DROP TABLE IF EXISTS videos CASCADE")
    op.execute("DROP TABLE IF EXISTS ar_content CASCADE")
    op.execute("DROP TABLE IF EXISTS clients CASCADE")
    op.execute("DROP TABLE IF EXISTS folders CASCADE")
    op.execute("DROP TABLE IF EXISTS projects CASCADE")
    op.execute("DROP TABLE IF EXISTS storage_connections CASCADE")
    op.execute("DROP TABLE IF EXISTS companies CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    
    # Создаем таблицы заново (будет сгенерировано автоматически при autogenerate)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # При откате просто создаем таблицы в обратном порядке
    pass
    # ### end Alembic commands ###
