"""add created_at and updated_at timestamps to ar_content table

Revision ID: 4f61ed1af7ca
Revises: e90dda773ba4
Create Date: 2025-12-22 14:14:27.306897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f61ed1af7ca'
down_revision: Union[str, None] = 'e90dda773ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.add_column('ar_content', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ar_content', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('ar_content', 'content_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.drop_index('ix_ar_content_company_id', table_name='ar_content')
    op.create_foreign_key(None, 'ar_content', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'ar_content', 'videos', ['active_video_id'], ['id'])
    op.create_foreign_key(None, 'ar_content', 'companies', ['company_id'], ['id'])
    op.add_column('ar_view_sessions', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('ar_view_sessions', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('ar_view_sessions', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('tracking_quality', sa.String(length=50), nullable=True))
    op.add_column('ar_view_sessions', sa.Column('video_played', sa.Boolean(), nullable=True))
    op.alter_column('ar_view_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('ar_view_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('ix_ar_view_sessions_session_id', table_name='ar_view_sessions')
    op.create_index(op.f('ix_ar_view_sessions_id'), 'ar_view_sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'ar_view_sessions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'ar_view_sessions', 'companies', ['company_id'], ['id'])
    op.drop_column('ar_view_sessions', 'location')
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('clients', sa.Column('is_active', sa.String(length=50), nullable=True))
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('email_queue', sa.Column('recipient_to', sa.String(length=255), nullable=False))
    op.add_column('email_queue', sa.Column('recipient_cc', sa.String(length=255), nullable=True))
    op.add_column('email_queue', sa.Column('recipient_bcc', sa.String(length=255), nullable=True))
    op.add_column('email_queue', sa.Column('html', sa.Text(), nullable=True))
    op.add_column('email_queue', sa.Column('template_id', sa.String(length=100), nullable=True))
    op.add_column('email_queue', sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('email_queue', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('email_queue', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('email_queue', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('email_queue', 'subject',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('email_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('email_queue', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_queue', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('email_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('email_queue', 'recipient_email')
    op.add_column('folders', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('folders', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('folders', sa.Column('folder_path', sa.String(length=500), nullable=True))
    op.add_column('folders', sa.Column('is_active', sa.String(length=50), nullable=True))
    op.add_column('folders', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'folders', 'projects', ['project_id'], ['id'])
    op.drop_column('folders', 'path')
    op.add_column('notifications', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('ar_content_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('email_error', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('telegram_sent', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('telegram_sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('telegram_error', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('subject', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('notifications_recipient_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_sender_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'sender_id')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'updated_at')
    op.alter_column('storage_connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('storage_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('storage_connections', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.alter_column('storage_folders', 'files_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage_folders', 'total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.add_column('video_rotation_schedules', sa.Column('rotation_type', sa.String(length=50), nullable=False))
    op.add_column('video_rotation_schedules', sa.Column('time_of_day', sa.Time(), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('day_of_month', sa.Integer(), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('cron_expression', sa.String(length=100), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('video_sequence', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('current_index', sa.Integer(), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('last_rotation_at', sa.DateTime(), nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('next_rotation_at', sa.DateTime(), nullable=True))
    op.alter_column('video_rotation_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=True)
    op.create_index(op.f('ix_video_rotation_schedules_id'), 'video_rotation_schedules', ['id'], unique=False)
    op.drop_column('video_rotation_schedules', 'end_date')
    op.drop_column('video_rotation_schedules', 'start_time')
    op.drop_column('video_rotation_schedules', 'end_time')
    op.drop_column('video_rotation_schedules', 'days_of_week')
    op.drop_column('video_rotation_schedules', 'name')
    op.drop_column('video_rotation_schedules', 'start_date')
    op.drop_column('video_rotation_schedules', 'schedule_type')
    op.add_column('video_schedules', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('video_schedules', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('video_schedules', 'start_time',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('video_schedules', 'end_time',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_video_schedules_video_id', table_name='video_schedules')
    op.create_index(op.f('ix_video_schedules_id'), 'video_schedules', ['id'], unique=False)
    op.drop_constraint('video_schedules_video_id_fkey', 'video_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'video_schedules', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_column('video_schedules', 'end_date')
    op.drop_column('video_schedules', 'is_active')
    op.drop_column('video_schedules', 'days_of_week')
    op.drop_column('video_schedules', 'start_date')
    op.drop_column('video_schedules', 'schedule_type')
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.drop_index('ix_videos_ar_content_id', table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_videos_ar_content_id', 'videos', ['ar_content_id'], unique=False)
    op.drop_column('videos', 'thumbnail_url')
    op.add_column('video_schedules', sa.Column('schedule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('video_schedules', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('video_schedules', sa.Column('days_of_week', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('video_schedules', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('video_schedules', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'video_schedules', type_='foreignkey')
    op.create_foreign_key('video_schedules_video_id_fkey', 'video_schedules', 'videos', ['video_id'], ['id'])
    op.drop_index(op.f('ix_video_schedules_id'), table_name='video_schedules')
    op.create_index('ix_video_schedules_video_id', 'video_schedules', ['video_id'], unique=False)
    op.alter_column('video_schedules', 'end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('video_schedules', 'start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('video_schedules', 'description')
    op.drop_column('video_schedules', 'status')
    op.add_column('video_rotation_schedules', sa.Column('schedule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('video_rotation_schedules', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('video_rotation_schedules', sa.Column('days_of_week', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('end_time', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('start_time', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('video_rotation_schedules', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_video_rotation_schedules_id'), table_name='video_rotation_schedules')
    op.alter_column('video_rotation_schedules', 'is_active',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('video_rotation_schedules', 'next_rotation_at')
    op.drop_column('video_rotation_schedules', 'last_rotation_at')
    op.drop_column('video_rotation_schedules', 'current_index')
    op.drop_column('video_rotation_schedules', 'video_sequence')
    op.drop_column('video_rotation_schedules', 'cron_expression')
    op.drop_column('video_rotation_schedules', 'day_of_month')
    op.drop_column('video_rotation_schedules', 'day_of_week')
    op.drop_column('video_rotation_schedules', 'time_of_day')
    op.drop_column('video_rotation_schedules', 'rotation_type')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('storage_folders', 'total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('storage_folders', 'files_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('storage_connections', 'metadata',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('storage_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('storage_connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notifications_sender_id_fkey', 'notifications', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('notifications_recipient_id_fkey', 'notifications', 'users', ['recipient_id'], ['id'])
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'telegram_error')
    op.drop_column('notifications', 'telegram_sent_at')
    op.drop_column('notifications', 'telegram_sent')
    op.drop_column('notifications', 'email_error')
    op.drop_column('notifications', 'email_sent_at')
    op.drop_column('notifications', 'email_sent')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'ar_content_id')
    op.drop_column('notifications', 'project_id')
    op.drop_column('notifications', 'company_id')
    op.add_column('folders', sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'sort_order')
    op.drop_column('folders', 'is_active')
    op.drop_column('folders', 'folder_path')
    op.drop_column('folders', 'description')
    op.drop_column('folders', 'project_id')
    op.add_column('email_queue', sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('email_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('email_queue', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('email_queue', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('email_queue', 'subject',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('email_queue', 'priority')
    op.drop_column('email_queue', 'last_error')
    op.drop_column('email_queue', 'max_attempts')
    op.drop_column('email_queue', 'variables')
    op.drop_column('email_queue', 'template_id')
    op.drop_column('email_queue', 'html')
    op.drop_column('email_queue', 'recipient_bcc')
    op.drop_column('email_queue', 'recipient_cc')
    op.drop_column('email_queue', 'recipient_to')
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'address')
    op.add_column('ar_view_sessions', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ar_view_sessions', type_='foreignkey')
    op.drop_constraint(None, 'ar_view_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_ar_view_sessions_id'), table_name='ar_view_sessions')
    op.create_index('ix_ar_view_sessions_session_id', 'ar_view_sessions', ['session_id'], unique=False)
    op.alter_column('ar_view_sessions', 'ip_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('ar_view_sessions', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('ar_view_sessions', 'video_played')
    op.drop_column('ar_view_sessions', 'tracking_quality')
    op.drop_column('ar_view_sessions', 'city')
    op.drop_column('ar_view_sessions', 'country')
    op.drop_column('ar_view_sessions', 'os')
    op.drop_column('ar_view_sessions', 'browser')
    op.drop_column('ar_view_sessions', 'device_type')
    op.drop_column('ar_view_sessions', 'company_id')
    op.drop_column('ar_view_sessions', 'project_id')
    op.drop_constraint(None, 'ar_content', type_='foreignkey')
    op.drop_constraint(None, 'ar_content', type_='foreignkey')
    op.drop_constraint(None, 'ar_content', type_='foreignkey')
    op.create_index('ix_ar_content_company_id', 'ar_content', ['company_id'], unique=False)
    op.alter_column('ar_content', 'content_metadata',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('ar_content', 'updated_at')
    op.drop_column('ar_content', 'created_at')
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.drop_table('audit_log')
    # ### end Alembic commands ###
