"""Add client fields to ar_content table

Revision ID: 20251209_add_client_fields_to_ar_content
Revises: 20251205_perf_idx
Create Date: 2025-12-09 15:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251209_add_client_fields_to_ar_content'
down_revision = '20251205_perf_idx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ar_content', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.add_column('ar_content', sa.Column('client_phone', sa.String(length=50), nullable=True))
    op.add_column('ar_content', sa.Column('client_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_content', 'client_email')
    op.drop_column('ar_content', 'client_phone')
    op.drop_column('ar_content', 'client_name')
    # ### end Alembic commands ###