"""add thumbnail_url field to ar_content table

Revision ID: a24b93e402c7
Revises: f224b2c1d30f
Create Date: 2025-12-18 19:59:46.634694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24b93e402c7'
down_revision: Union[str, None] = 'f224b2c1d30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ar_content', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_content', 'thumbnail_url')
    # ### end Alembic commands ###
