"""Add thumbnail_url fields to ar_content and videos tables

Revision ID: 20251210_add_thumbnail_url_fields
Revises: 20251209_add_client_fields_to_ar_content
Create Date: 2025-12-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251210_add_thumbnail_url_fields'
down_revision = '20251209_add_client_fields_to_ar_content'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Get existing columns for ar_content
    inspector = sa.inspect(conn)
    ar_content_columns = [col['name'] for col in inspector.get_columns('ar_content')]
    
    # Add thumbnail_url to ar_content if it doesn't exist
    if 'thumbnail_url' not in ar_content_columns:
        op.add_column('ar_content', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    
    # Get existing columns for videos
    videos_columns = [col['name'] for col in inspector.get_columns('videos')]
    
    # Add thumbnail_url to videos if it doesn't exist
    if 'thumbnail_url' not in videos_columns:
        op.add_column('videos', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('ar_content', 'thumbnail_url')
    # ### end Alembic commands ###