"""new_migration_fix

Revision ID: 8f2c4b8e6d9a
Revises: 3d2b8a4fd05b
Create Date: 2025-12-15 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2c4b8e6d9a'
down_revision: Union[str, None] = '3d2b8a4fd05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable UUID extension
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    
    # Create tables in correct order (parents first)
    
    # 1. USERS TABLE
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False, server_default='admin'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('login_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    
    # 2. COMPANIES TABLE
    op.create_table('companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_id', 'companies', ['id'], unique=False)
    
    # 3. PROJECTS TABLE
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='active'),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    
    # 4. VIDEOS TABLE (создаем без внешнего ключа на ar_content)
    op.create_table('videos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ar_content_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('video_path', sa.String(length=500), nullable=True),
        sa.Column('video_url', sa.String(length=500), nullable=True),
        sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
        sa.Column('preview_url', sa.String(length=500), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='uploaded'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('rotation_type', sa.String(length=20), nullable=False, server_default='none'),
        sa.Column('rotation_order', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('subscription_end', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_ar_content_id', 'videos', ['ar_content_id'], unique=False)
    op.create_index('ix_videos_id', 'videos', ['id'], unique=False)
    
    # 5. AR_CONTENT TABLE (теперь можем добавить внешний ключ на videos)
    op.create_table('ar_content',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('active_video_id', sa.Integer(), nullable=True),
        sa.Column('unique_id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('order_number', sa.String(length=50), nullable=False),
        sa.Column('customer_name', sa.String(length=255), nullable=True),
        sa.Column('customer_phone', sa.String(length=50), nullable=True),
        sa.Column('customer_email', sa.String(length=255), nullable=True),
        sa.Column('duration_years', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
        sa.Column('content_metadata', postgresql.JSON().with_variant(postgresql.JSONB, 'postgresql'), nullable=True),
        sa.Column('photo_path', sa.String(length=500), nullable=True),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('video_path', sa.String(length=500), nullable=True),
        sa.Column('video_url', sa.String(length=500), nullable=True),
        sa.Column('qr_code_path', sa.String(length=500), nullable=True),
        sa.Column('qr_code_url', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['active_video_id'], ['videos.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('unique_id')
    )
    op.create_index('ix_ar_content_company_id', 'ar_content', ['company_id'], unique=False)
    op.create_index('ix_ar_content_id', 'ar_content', ['id'], unique=False)
    op.create_index('ix_ar_content_project_id', 'ar_content', ['project_id'], unique=False)
    op.create_index('ix_ar_content_project_order', 'ar_content', ['project_id', 'order_number'], unique=True)
    
    # Добавляем внешний ключ для videos -> ar_content после создания ar_content
    op.create_foreign_key('fk_videos_ar_content_id', 'videos', 'ar_content', ['ar_content_id'], ['id'], ondelete='CASCADE')
    
    # Add constraints
    op.create_check_constraint('check_duration_years', 'ar_content', 'duration_years IN (1, 3, 5)')
    op.create_check_constraint('check_views_count_non_negative', 'ar_content', 'views_count >= 0')
    
    # Insert default admin user
    op.execute("""
        INSERT INTO users (email, hashed_password, full_name, role, is_active)
        VALUES (
            'admin@vertexar.com',
            '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIxF2PQaDi',  -- admin123
            'Vertex AR Admin',
            'admin',
            true
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order (children first)
    op.drop_table('ar_content')
    op.drop_table('videos')
    op.drop_table('projects')
    op.drop_table('companies')
    op.drop_table('users')
    
    # Drop indexes
    op.drop_index('ix_videos_id', table_name='videos')
    op.drop_index('ix_videos_ar_content_id', table_name='videos')
    op.drop_index('ix_ar_content_project_order', table_name='ar_content')
    op.drop_index('ix_ar_content_project_id', table_name='ar_content')
    op.drop_index('ix_ar_content_id', table_name='ar_content')
    op.drop_index('ix_ar_content_company_id', table_name='ar_content')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_company_id', table_name='projects')
    op.drop_index('ix_companies_id', table_name='companies')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    
    # Drop constraints
    op.drop_constraint('check_views_count_non_negative', 'ar_content', type_='check')
    op.drop_constraint('check_duration_years', 'ar_content', type_='check')
    op.drop_constraint('fk_videos_ar_content_id', 'videos', type_='foreignkey')
    
    # Drop extension
    op.execute("DROP EXTENSION IF EXISTS \"uuid-ossp\"")
    # ### end Alembic commands ###