"""add created_at and updated_at timestamps to ar_content table

Revision ID: 20251222_1420_add_timestamps
Revises: e90dda773ba4
Create Date: 2025-12-22 14:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '20251222_1420_add_timestamps'
down_revision: Union[str, None] = 'e90dda773ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ar_content', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ar_content', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ar_content', 'updated_at')
    op.drop_column('ar_content', 'created_at')
    # ### end Alembic commands ###