"""seed initial admin user and default company

Revision ID: a1b2c3d4e5f6
Revises: 44af7900a836
Create Date: 2025-06-23 10:00:00.000000

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '44af7900a836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Password hashing context
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if admin user already exists
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT id FROM users WHERE email = 'admin@vertex.local'")
    ).fetchone()
    
    if not result:
        # Hash the admin password
        admin_password_hash = pwd_context.hash("admin123")
        
        # Insert admin user
        connection.execute(
            sa.text("""
                INSERT INTO users (email, hashed_password, full_name, role, is_active, created_at, updated_at)
                VALUES (:email, :hashed_password, :full_name, :role, :is_active, :created_at, :updated_at)
            """),
            {
                'email': 'admin@vertex.local',
                'hashed_password': admin_password_hash,
                'full_name': 'System Administrator',
                'role': 'admin',
                'is_active': True,
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow()
            }
        )
        print("Created admin user: admin@vertex.local")
    else:
        print("Admin user already exists, skipping creation")
    
    # Check if default company already exists
    result = connection.execute(
        sa.text("SELECT id FROM companies WHERE name = 'Vertex AR'")
    ).fetchone()
    
    if not result:
        # Insert default company
        connection.execute(
            sa.text("""
                INSERT INTO companies (name, slug, contact_email, status, created_at, updated_at)
                VALUES (:name, :slug, :contact_email, :status, :created_at, :updated_at)
            """),
            {
                'name': 'Vertex AR',
                'slug': 'vertex-ar',
                'contact_email': 'admin@vertex.local',
                'status': 'active',
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow()
            }
        )
        print("Created default company: Vertex AR")
    else:
        print("Default company already exists, skipping creation")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Delete admin user if it exists
    connection.execute(
        sa.text("DELETE FROM users WHERE email = 'admin@vertex.local'")
    )
    print("Deleted admin user: admin@vertex.local")
    
    # Delete default company if it exists
    connection.execute(
        sa.text("DELETE FROM companies WHERE name = 'Vertex AR'")
    )
    print("Deleted default company: Vertex AR")
    
    # ### end Alembic commands ###